# Generated by Django 2.1 on 2020-05-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.CharField(db_column='commodity_ID', max_length=20, primary_key=True, serialize=False)),
                ('commodity_name', models.CharField(max_length=45)),
                ('price', models.FloatField()),
                ('place_of_delivery', models.CharField(blank=True, max_length=45, null=True)),
                ('commodity_specification', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'commodity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommodityCatalog',
            fields=[
                ('commodity_catalog_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('commodity_catalog_name', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'commodity_catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'follow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('order_form_id', models.CharField(db_column='order_form_ID', max_length=20, primary_key=True, serialize=False)),
                ('shop_id', models.CharField(db_column='shop_ID', max_length=20)),
                ('freight', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('deliver_time', models.DateTimeField(blank=True, null=True)),
                ('deal_time', models.DateTimeField(blank=True, null=True)),
                ('receive_address', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'order_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderFormCatalog',
            fields=[
                ('order_form_catalog_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('order_form_catalog_name', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'order_form_catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderFormCommodity',
            fields=[
                ('commodity_pc', models.PositiveIntegerField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'order_form_commodity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.CharField(db_column='refund_ID', max_length=20, primary_key=True, serialize=False)),
                ('commodity_id', models.CharField(db_column='commodity_ID', max_length=20)),
                ('refund_reason', models.CharField(max_length=50)),
                ('refund_quantity', models.PositiveIntegerField()),
                ('apply_time', models.DateTimeField()),
                ('refund_time', models.DateTimeField(blank=True, null=True)),
                ('refund_catalog', models.IntegerField()),
            ],
            options={
                'db_table': 'refund',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('inventory', models.PositiveIntegerField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sells',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.CharField(db_column='shop_ID', max_length=20, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=45)),
                ('shop_reg_date', models.DateField()),
            ],
            options={
                'db_table': 'shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'shopping_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(db_column='user_ID', max_length=20, primary_key=True, serialize=False)),
                ('phone_num', models.CharField(max_length=11)),
                ('log_in_state', models.IntegerField()),
                ('user_reg_date', models.DateField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPrivacy',
            fields=[
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user_privacy',
                'managed': False,
            },
        ),
    ]
